import unittest

from fastapi.testclient import TestClient

from src.api.main import app


class WebUITests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.client = TestClient(app)

    def test_root_serves_web_ui(self):
        response = self.client.get("/")

        self.assertEqual(response.status_code, 200)
        self.assertIn("text/html", response.headers["content-type"])
        self.assertIn("Reliable Scientific Paper Copilot", response.text)
        self.assertIn("Upload a PDF", response.text)
        self.assertIn("Source label (optional)", response.text)
        self.assertIn("Source URL (optional)", response.text)
        self.assertIn("Citation hint (optional)", response.text)
        self.assertIn("Ask a question", response.text)
        self.assertIn("Selected paper details", response.text)
        self.assertIn("Filter papers by title, file name, or id", response.text)
        self.assertIn("No papers loaded yet.", response.text)
        self.assertIn("Paper library snapshot", response.text)
        self.assertIn("Copy library snapshot", response.text)
        self.assertIn("Download library snapshot", response.text)
        self.assertIn("Loading library summary...", response.text)
        self.assertIn("Demo question presets", response.text)
        self.assertIn("Load preset question", response.text)
        self.assertIn("No demo presets loaded yet.", response.text)
        self.assertIn("Retrieval mode", response.text)
        self.assertIn("Hybrid fusion", response.text)
        self.assertIn('id="retrieval-preset-status"', response.text)

    def test_web_ui_surfaces_richer_paper_metadata_sections(self):
        response = self.client.get("/")

        self.assertIn("Automated ingestion notes", response.text)
        self.assertIn("Operator notes", response.text)
        self.assertIn("Abstract preview", response.text)
        self.assertIn("Extracted datasets", response.text)
        self.assertIn("Evidence", response.text)
        self.assertIn("Copy paper brief", response.text)
        self.assertIn("Download paper brief", response.text)
        self.assertIn("Export activity transcript", response.text)
        self.assertIn("Copy activity transcript", response.text)
        self.assertIn("Download activity transcript", response.text)
        self.assertIn("Clear question history", response.text)
        self.assertIn("Export demo recap", response.text)
        self.assertIn("Copy demo recap", response.text)
        self.assertIn("Download demo recap", response.text)
        self.assertIn("Export operator metadata history", response.text)
        self.assertIn("Copy metadata history", response.text)
        self.assertIn("Download metadata history", response.text)
        self.assertIn("Copy or download the five most recent paper questions as a shareable Markdown transcript, or clear saved question history to reset a live demo.", response.text)
        self.assertIn("Copy or download one Markdown handoff that combines the paper brief with the recent activity recap.", response.text)
        self.assertIn("Copy or download the recent saved operator metadata edits as Markdown for provenance review or demo handoff.", response.text)
        self.assertIn("Delete paper", response.text)
        self.assertIn("Recent activity summary", response.text)
        self.assertIn("Recent question history", response.text)
        self.assertIn("Operator metadata history", response.text)
        self.assertIn("Edit operator metadata", response.text)
        self.assertIn("Source label", response.text)
        self.assertIn("Source URL", response.text)
        self.assertIn("Citation hint", response.text)
        self.assertIn("Save metadata", response.text)
        self.assertIn("function updatePaperDetails", response.text)
        self.assertIn("function renderEvidence", response.text)
        self.assertIn("function renderAnswer", response.text)
        self.assertIn("function flattenDemoQuestions", response.text)
        self.assertIn("function renderQuestionPresetOptions", response.text)
        self.assertIn("function updateQuestionPresetMeta", response.text)
        self.assertIn("function loadSelectedQuestionPreset", response.text)
        self.assertIn("function buildPaperSearchText", response.text)
        self.assertIn("function sortPapersByRecency", response.text)
        self.assertIn("function getVisiblePapers", response.text)
        self.assertIn("function renderPaperOptions", response.text)
        self.assertIn("function renderPaperLibrarySummary", response.text)
        self.assertIn("function fetchPaperBriefMarkdown", response.text)
        self.assertIn("function fetchPaperLibrarySummary", response.text)
        self.assertIn("function fetchPaperLibrarySummaryMarkdown", response.text)
        self.assertIn("function fetchPaperActivity", response.text)
        self.assertIn("function fetchPaperActivityTranscript", response.text)
        self.assertIn("function fetchPaperDemoRecapMarkdown", response.text)
        self.assertIn("function fetchPaperMetadataHistoryMarkdown", response.text)
        self.assertIn("function handleLibrarySummaryAction", response.text)
        self.assertIn("function handleActivityTranscriptAction", response.text)
        self.assertIn("function handleDemoRecapAction", response.text)
        self.assertIn("function handleMetadataHistoryAction", response.text)
        self.assertIn("function savePaperMetadata", response.text)
        self.assertIn("function parseOperatorNotes", response.text)
        self.assertIn("function populateMetadataEditor", response.text)
        self.assertIn("function formatActivityRetrievalConfig", response.text)
        self.assertIn("function summarizeActivityItems", response.text)
        self.assertIn("function renderActivitySummary", response.text)
        self.assertIn("function renderActivityItems", response.text)
        self.assertIn("function reuseRecentQuestion", response.text)
        self.assertIn("Reuse question", response.text)
        self.assertIn("reuse-question-button", response.text)
        self.assertIn("Answer:</strong>", response.text)
        self.assertIn("Evidence cues:", response.text)
        self.assertIn("Retrieval:", response.text)
        self.assertIn("function formatTimestamp", response.text)
        self.assertIn("function normalizeRetrievalUiState", response.text)
        self.assertIn("function getInitialUiState", response.text)
        self.assertIn("function syncUrlState", response.text)
        self.assertIn("function applyRetrievalUiState", response.text)
        self.assertIn("function renderRetrievalPresetStatus", response.text)
        self.assertIn("function renderMetadataHistory", response.text)
        self.assertIn("Update ${Number(item.operator_update_count || 0) || \"?\"}", response.text)
        self.assertIn("Source URL saved", response.text)
        self.assertIn("history-item", response.text)
        self.assertIn("function handleBriefAction", response.text)
        self.assertIn("function handleDeletePaper", response.text)
        self.assertIn("function handleClearPaperActivity", response.text)
        self.assertIn("window.confirm(`Delete ${paperLabel}? This removes the paper and its saved artifacts.`)", response.text)
        self.assertIn("window.confirm(`Clear saved question history for ${paperLabel}? This keeps the paper but removes recent activity for demo reset.`)", response.text)
        self.assertIn("citation-anchor", response.text)
        self.assertIn("is-highlighted", response.text)

    def test_web_ui_references_existing_api_routes(self):
        response = self.client.get("/")

        self.assertIn('fetch("/upload"', response.text)
        self.assertIn('formData.append("source_label", uploadSourceLabelInput.value.trim())', response.text)
        self.assertIn('formData.append("source_url", uploadSourceUrlInput.value.trim())', response.text)
        self.assertIn('formData.append("citation_hint", uploadCitationHintInput.value.trim())', response.text)
        self.assertIn('fetch("/ask"', response.text)
        self.assertIn('fetch("/papers"', response.text)
        self.assertIn('fetch("/papers/summary")', response.text)
        self.assertIn('fetch("/papers/summary/export")', response.text)
        self.assertIn('fetch("/health"', response.text)
        self.assertIn('fetch("/demo/question-presets")', response.text)
        self.assertIn('fetch(`/papers/${paperId}/brief/export`)', response.text)
        self.assertIn('fetch(`/papers/${paperId}/activity?limit=5`)', response.text)
        self.assertIn('fetch(`/papers/${paperId}/activity/export?limit=5`)', response.text)
        self.assertIn('fetch(`/papers/${paperId}/activity`, { method: "DELETE" })', response.text)
        self.assertIn('fetch(`/papers/${paperId}/demo-recap/export?activity_limit=5`)', response.text)
        self.assertIn('fetch(`/papers/${paperId}/metadata/history/export?limit=10`)', response.text)
        self.assertIn('fetch(`/papers/${paperId}/metadata`, {', response.text)
        self.assertIn('method: "PATCH"', response.text)
        self.assertIn('fetch(`/papers/${paperId}`, { method: "DELETE" })', response.text)
        self.assertIn('questionPresetSelect.addEventListener("change"', response.text)
        self.assertIn('retrievalModeInput.addEventListener("change"', response.text)
        self.assertIn('for (const input of [topKInput, denseWeightInput, lexicalWeightInput, rrfKInput])', response.text)
        self.assertIn('params.get("paper_id") || ""', response.text)
        self.assertIn('params.get("question_preset") || ""', response.text)
        self.assertIn('params.get("retrieval_mode") || "dense"', response.text)
        self.assertIn('topK: params.get("top_k")', response.text)
        self.assertIn('denseWeight: params.get("dense_weight")', response.text)
        self.assertIn('lexicalWeight: params.get("lexical_weight")', response.text)
        self.assertIn('rrfK: params.get("rrf_k")', response.text)
        self.assertIn('const allowedRetrievalModes = new Set(["dense", "lexical", "hybrid"])', response.text)
        self.assertIn('const topK = Math.min(10, Math.max(1, rawTopK));', response.text)
        self.assertIn('const denseWeight = rawDenseWeight >= 0 ? rawDenseWeight : 1.0;', response.text)
        self.assertIn('const lexicalWeight = rawLexicalWeight >= 0 ? rawLexicalWeight : 1.0;', response.text)
        self.assertIn('const rrfK = rawRrfK >= 1 ? rawRrfK : 60;', response.text)
        self.assertIn('history.replaceState({}, "", `${url.pathname}${url.search}${url.hash}`)', response.text)
        self.assertIn('url.searchParams.set("paper_id", paperId)', response.text)
        self.assertIn('url.searchParams.set("question_preset", questionPreset)', response.text)
        self.assertIn('url.searchParams.set("retrieval_mode", normalizedState.retrievalMode)', response.text)
        self.assertIn('url.searchParams.set("top_k", String(normalizedState.topK))', response.text)
        self.assertIn('url.searchParams.set("dense_weight", String(normalizedState.denseWeight))', response.text)
        self.assertIn('url.searchParams.set("lexical_weight", String(normalizedState.lexicalWeight))', response.text)
        self.assertIn('url.searchParams.set("rrf_k", String(normalizedState.rrfK))', response.text)
        self.assertIn('loadQuestionPresetButton.addEventListener("click"', response.text)
        self.assertIn('paperSearchInput.addEventListener("input"', response.text)
        self.assertIn('syncUrlState({ paperId: nextPaperId });', response.text)
        self.assertIn('paperSelect.addEventListener("change"', response.text)
        self.assertIn('syncUrlState({ paperId: event.target.value });', response.text)
        self.assertIn('paperActivity.addEventListener("click"', response.text)
        self.assertIn('reuseRecentQuestion(button.dataset.question || "")', response.text)
        self.assertIn('questionInput.focus();', response.text)
        self.assertIn('copyLibrarySummaryButton.addEventListener("click"', response.text)
        self.assertIn('downloadLibrarySummaryButton.addEventListener("click"', response.text)
        self.assertIn('copyBriefButton.addEventListener("click"', response.text)
        self.assertIn('downloadBriefButton.addEventListener("click"', response.text)
        self.assertIn('copyActivityButton.addEventListener("click"', response.text)
        self.assertIn('downloadActivityButton.addEventListener("click"', response.text)
        self.assertIn('clearActivityButton.addEventListener("click"', response.text)
        self.assertIn('copyDemoRecapButton.addEventListener("click"', response.text)
        self.assertIn('downloadDemoRecapButton.addEventListener("click"', response.text)
        self.assertIn('copyMetadataHistoryButton.addEventListener("click"', response.text)
        self.assertIn('downloadMetadataHistoryButton.addEventListener("click"', response.text)
        self.assertIn('deletePaperButton.addEventListener("click"', response.text)
        self.assertIn('saveMetadataButton.addEventListener("click"', response.text)
        self.assertIn('last_operator_update_source: "web-ui"', response.text)
        self.assertIn('navigator.clipboard.writeText(summaryMarkdown)', response.text)
        self.assertIn('Clipboard copy is unavailable in this browser. The library snapshot preview is open below, or you can use Download instead.', response.text)
        self.assertIn('Could not copy the library snapshot to the clipboard.', response.text)
        self.assertIn('Could not download the library snapshot.', response.text)
        self.assertIn('navigator.clipboard.writeText(briefMarkdown)', response.text)
        self.assertIn('navigator.clipboard.writeText(transcriptMarkdown)', response.text)
        self.assertIn('navigator.clipboard.writeText(recapMarkdown)', response.text)
        self.assertIn('navigator.clipboard.writeText(metadataHistoryMarkdown)', response.text)
        self.assertIn('URL.createObjectURL(blob)', response.text)
        self.assertIn('Showing ${visibleCount} of ${totalCount} ${suffix}, newest first.', response.text)
        self.assertIn('${totalCount} ${suffix} available, newest first.', response.text)
        self.assertIn('await refreshPapers();', response.text)
        self.assertIn('await updatePaperDetails(paperId);', response.text)
        self.assertIn('applyRetrievalUiState(initialUiState);', response.text)
        self.assertIn('renderRetrievalPresetStatus(initialUiState);', response.text)
        self.assertIn('setStatus(retrievalPresetStatus, `Adjusted invalid retrieval URL preset values: ${issues.join(", ")}.`, "error")', response.text)
        self.assertIn('refreshPapers(initialUiState.paperId);', response.text)
        self.assertIn('refreshDemoQuestionPresets(initialUiState.questionPreset);', response.text)
        self.assertIn('retrieval_mode: retrievalMode', response.text)
        self.assertIn('renderRetrievalScores(payload)', response.text)
        self.assertIn('mode=${item.retrieval_mode || "dense"}', response.text)
        self.assertIn('dense=${Number(item.dense_weight).toFixed(1)}', response.text)
        self.assertIn('lexical=${Number(item.lexical_weight).toFixed(1)}', response.text)
        self.assertIn('id="retrieval-scores-table"', response.text)

    def test_demo_question_presets_endpoint_returns_packaged_questions(self):
        response = self.client.get("/demo/question-presets")

        self.assertEqual(response.status_code, 200)
        payload = response.json()
        self.assertGreaterEqual(len(payload), 1)
        first_set = payload[0]
        self.assertIn("package_id", first_set)
        self.assertIn("questions", first_set)
        self.assertGreaterEqual(len(first_set["questions"]), 1)
        self.assertIn("question", first_set["questions"][0])

    def test_demo_recap_export_endpoint_is_available(self):
        response = self.client.get("/openapi.json")

        self.assertEqual(response.status_code, 200)
        self.assertIn("/papers/{paper_id}/demo-recap/export", response.text)


if __name__ == "__main__":
    unittest.main()
